title: "patrickhyatt.com"
url: "https://www.patrickhyatt.com"
excerpt_separator: <!--excerpt-->

#author:
name: "Patrick Hyatt"
email: "patrick.hyatt@gmail.com"
twitter: "https://www.twitter.com/patrickHyatt"
stackoverflow: "https://stackoverflow.com/users/36/pat"
github: "https://www.github.com/patHyatt"
linkedin: "https://www.linkedin.com/in/patrickhyatt"
hackernews: "https://news.ycombinator.com/user?id=PatHyatt"
instagram: "https://www.instagram.com/patrick.hyatt/"

plugins:
  - jekyll-redirect-from

sass:
  style: compressed

kramdown:
  input: GFM

compress_html:
  clippings: []
  comments: ['all']
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

exclude: [README.md, Gemfile, Gemfile.lock]
