title: "patrickhyatt.com"
url: "http://www.patrickhyatt.com"

#author:
name: "Patrick Hyatt"
email: "patrick.hyatt@gmail.com"
twitter: "https://www.twitter.com/patrickHyatt"
stackoverflow: "https://stackoverflow.com/users/36/pat"
github: "https://www.github.com/patHyatt"
linkedin: "https://www.linkedin.com/in/patrickhyatt"
hackernews: "https://news.ycombinator.com/user?id=PatHyatt"

sass:
  style: compressed

kramdown:
  input: GFM

paginate: 5

exclude: [README.markdown, package.json, node_modules, Gemfile, Gemfile.lock]
